name: Docker Image CI
on:
  push:
    branches: [ v24 ]
  pull_request:
    branches: [ v24 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build project with Maven
      run:  mvn clean compile -DskipTests  package --file pom.xml
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
